### ISSUE TITLE
Upgrade dependencies in Gatsby theme, OSS site, Dev site, and Docs site

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/gatsby-theme-newrelic#345]
## Summary
In preparation for upgrading to Gatsby 3, we want to update all of the core dependencies first.

Core dependencies to update:
- [ ] Node 12
- [ ] React 17
- [ ] Emotion 11

Core dependencies to _not_ update (too difficult to update):
- [ ] Webpack 5
- [ ] GraphQL 15
- [ ] ESLint 7
- [ ] Remark 13

## Acceptance Criteria 
- [ ] Gatsby theme updated
- [ ] OSS site updated
- [ ] Dev site updated
- [ ] Docs site updated

**Comment by aswanson-nr** [comment]
Here is a table to list the current status:

| Dependency | Gatsby theme | OSS site | Dev site | Docs site |
|--------------|--------------|--------|----------|--------|
| Node 12 | | | | |
| Webpack 5 | | | | |
| React 17 | | | | |
| GraphQL 15 | | | | |
| ESLint 7 | | | | |
| Remark 13 | | | | |
| Emotion 11 | | | | |

**Comment by aswanson-nr** [comment]
Broken off from this umbrella issue https://github.com/newrelic/docs-website/issues/1184

**Comment by zstix** [comment]
We're going to close this ticket since most of the decencies break the site _without_ Gatsby v3. We incorporate the points into #346
