### ISSUE TITLE
Implement One Trust for cookie acceptance and GDPR compliance tracking

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#347]
One Trust is a product that is currently going to be used by New Relic to manage cookie acceptance and GDPR compliance,  we'll need to implement this and integrate it into our theme for use on the Dev, OSS, and eventually the Docs sites.

### References

https://www.onetrust.com/products/cookie-consent/

### Acceptance Criteria

- [x] Confirm with David Hwang if this vendor is selected and what the implementation timeline is
- [x] Get access to one trust admin panel in OKTA to begin testing it out
- [x] Setup functional cookies (like dark mode) without opt-in (aka: essential cookies) in One Trust
- [x] Apply this change to the DEV site.
- [x] Apply this change to the OSS site.
- [x] Run before and after [lighthouse tests](https://web.dev/measure/) for each site to understand perf impacts of this change.
- [x] Work with David and Analytics team: `Zoe Zhou` to validate analytics and other is still working
- [x] 🍪 🍪 testing successful
- [x] Create a follow up ticket to enable this feature on the Docs Site for post `I/O GA`

### Other considerations 🍪 

-  [x] Does the cookie tracking component just go away after a period of time, we should keep prompting a user until they accept / deny ideally?
- [X] Can we make the GDPR prompt more pronounced, and more of an overlay effect where the site isn't usable until they accept / deny.
- [X] What type of custom CSS is required to ensure the js widget matches our site design
>  if a user declines all cookies, we get no data  but we default to opting in all users unless they explicitly opt out. 
>  one set of opt in or out applies to all sites with one trust, so the user only has to do this once for all external sites.
> marketing will set the user exp. for the one trust dialog we just render whatever is provided to us.

- [x] Dark mode is cookie-dependent, how will this work impact it?

> see above about essential cookies to One Trust. 

- [x] We are also looking at using a cookie to pass pack information (identifier of pack) to the signup flow, so we’ll need to consider that as well

> see above about essential cookies to One Trust. 
> we can test this case in our system test plan.

- [x] How does this get added to the page (is there a JS snippet)?
 > yes
- [x] Do we understand the performance impact of adding this?
> we can run before an after lighthouse tests
- [x] If we add this snippet, can we remove any other cookie code (does this replace something)?
> we can remove our custom cookie component.

**Comment by zstix** [comment]
Couple of questions around this:
* [ ] How does this get added to the page (is there a JS snippet)?
* [ ] Do we understand the performance impact of adding this?
* [ ] If we add this snippet, can we remove any other cookie code (does this replace something)?

**Comment by jpvajda** [comment]
after discussing as a team , this is at least an 8pt effort and could be as large as 13pts.

**Comment by jpvajda** [comment]
I passed this information over to David and Stijn for consideration...

**Comment by zstix** [comment]
Let's collect some information about how difficult this is and what the impact is on our sites (e.g. dark mode).

**Comment by zstix** [comment]
Here are the scripts for One Trust. We should use the _test_ script for the moment, and then swap over to the _production_ script once everything is set up. These scripts are to be added in the `<head>` of each page.

## opensource.newrelic.com

### Test Script
```html
<!-- OneTrust Cookies Consent Notice start for opensource.newrelic.com -->
<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="971b8f59-9199-438a-b638-763f94671811-test" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>
<!-- OneTrust Cookies Consent Notice end for opensource.newrelic.com -->
```

### Production Script
```html
<!-- OneTrust Cookies Consent Notice start for opensource.newrelic.com -->
<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="971b8f59-9199-438a-b638-763f94671811" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>
<!-- OneTrust Cookies Consent Notice end for opensource.newrelic.com -->
```

## developer.newrelic.com

### Test Script
```html
<!-- OneTrust Cookies Consent Notice start for developer.newrelic.com -->
<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="77dd4d78-49db-4057-81ea-4bc325d6ecdd-test" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>
<!-- OneTrust Cookies Consent Notice end for developer.newrelic.com -->
```

### Production Script
```html
<!-- OneTrust Cookies Consent Notice start for developer.newrelic.com -->
<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="77dd4d78-49db-4057-81ea-4bc325d6ecdd" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>
<!-- OneTrust Cookies Consent Notice end for developer.newrelic.com -->
```

## docs.newrelic.com
At the moment, we are not implementing One Trust on the docs site.

**Comment by davidhwang** [comment]
For docs.newrelic.com:

Test script:

`


<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="e66f9ef1-3a12-4043-b7c0-1a2ea66f6d41-test" ></script>

<script type="text/javascript">

function OptanonWrapper() { }

</script>


`

Production script:
`

<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="e66f9ef1-3a12-4043-b7c0-1a2ea66f6d41" ></script>

<script type="text/javascript">

function OptanonWrapper() { }

</script>

`

**Comment by zstix** [comment]
This has been released in the theme. Here's what we need to do to wrap up this work:
* [ ] Update the theme to the latest version & add the `oneTrustID` for the developer site
* [ ] Update the theme to the latest version & add the `oneTrustID` for the oss site
* [ ] Update the theme to the latest version & add the `oneTrustID` for the docs site (if we want to just knock it out)
