### ISSUE TITLE
[Public Catalog] Update global header for I/O

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/gatsby-theme-newrelic#438]
## Summary

Update global header to include link to New Relic I/O in the nav menus (mobile and desktop).

### Mock Up 

<img width="215" alt="Screen Shot 2021-08-27 at 3 44 45 PM" src="https://user-images.githubusercontent.com/1395158/131191804-a998b659-4b9b-4be5-9dbe-2bc55fb9cbef.png">

## Acceptance criteria
- [x] When viewing either the quick starts landing or a details page, the New Relic I/O menu item has a darker background color (and not Developer)
- [x] The link element should be called `Instant Observability`
- [x] This element should be `LAST`  in the header

**Comment by jpvajda** [comment]
Confirmed this should go last in the  nav order.

**Comment by jpvajda** [comment]
To keep things simple and ensure that there are no issues with Google, we are going to leave I/O on developer.newrelic.com for the September launch. 

We'll use a wildcard redirect in tandem with the new marketplace site domain that is set to go live in October 
This will be a clean 301 redirect TO the developer.newrelic.com/instant-observability/ subfolder FROM newrelic.com/instant-observability) .

Therefore in the case of this button it should point to `https://developer.newrelic.com/instant-observability/` IMHO

**Comment by rudouglas** [comment]
Cool thanks @jpvajda I might point it to `https://observabilitypacks.gatsbyjs.io/instant-observability/` for now so we have a working link and then add that as a change we need for production readiness after the  merge of the feature branch

**Comment by jpvajda** [comment]
@rudouglas can u file a follow up ticket to set this correctly and label it `readiness`? - Thanks!

**Comment by rudouglas** [comment]
Yessir
#450 
![](https://user-images.githubusercontent.com/17122543/132008657-408b7d09-6a2d-49dd-95ca-55082a4af8aa.png)

**Comment by jpvajda** [comment]
Confirmed: The logo will be ready on Sept 10
