### ISSUE TITLE
[SwiftType] Add quick starts to swiftype query filters

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/gatsby-theme-newrelic#439]
## Summary

Update global header search and docs/developer related resources queries to surface quick starts in results.

### Add IO to `type` filter

Add quick starts to the `type` filter in swiftype queries. The `type` = `quick_starts`.

Relevant queries to update include:
* Theme: [global header search filters](https://github.com/newrelic/gatsby-theme-newrelic/blob/072abffad44fa78e458a97f896abd7067aba656a/packages/gatsby-theme-newrelic/src/components/SearchModal/SearchModal.js#L20)
* Docs: [related resources query](https://github.com/newrelic/docs-website/blob/develop/scripts/actions/get-related-resources.js)
* Developer: [related resources query](https://github.com/newrelic/developer-website/blob/develop/gatsby-config.js)

### Add quick start name to weighted fields

We also want to update the swiftype queries for related resources (linked above) to also search the `quick_start_name` field and weight it to 8 (we can adjust once quick start pages are indexed and we see results).

```
...
search_fields: {
  page: ['tags^10', 'quick_start_name^8, 'body^5', 'title^1.5', '*'],
},
...
```
### Update label

By default, the label will be `QUICK_STARTS`. I think we will want it to be: `QUICK STARTS`. Update [Result component logic](https://github.com/newrelic/gatsby-theme-newrelic/blob/072abffad44fa78e458a97f896abd7067aba656a/packages/gatsby-theme-newrelic/src/components/SearchModal/Result.js#L67) to remove the `_`

### Notes
The `type` field is used to identify which domain/site the page belongs to. Since quick starts are kinda / will be their own site, this sets us up longer term.

None of the other public sites seem to filter on `type`, so no need to update queries there.

## Acceptance criteria
- [x] The global header includes filter for `quick_starts` type
- [x] The docs related resources query includes filter for `quick_starts` type, and includes quick starts in weighted search fields
- [x] The developer related resources query includes filter for `quick_starts` type, and includes quick starts in weighted search fields

## Helpful links
- [Add meta tags to details pages](https://github.com/newrelic/developer-website/issues/1539)

**Comment by rudouglas** [comment]
Updates to Theme: https://github.com/newrelic/gatsby-theme-newrelic/pull/446
Updates to Dev Site: https://github.com/newrelic/developer-website/pull/1582
Updates to Docs site: https://github.com/newrelic/docs-website/pull/3762

**Comment by rudouglas** [comment]
All PR's are now merged
