### ISSUE TITLE
Deprecate the custom cookie management tooling, anonymous tracking

### ISSUE THREAD

**Issue by jpvajda** [newrelic/gatsby-theme-newrelic#454]
## Summary

In order to fully cut over to new cookie management tool (OneTrust) and deprecate the old cookie management tooling, we need to remove code related to `newrelic-gdpr-consent` cookie, Google Analytics, and the `CookieConsentDialog` component.

### Current behavior

OneTrust is officially supported via the theme if a site adds a `oneTrustID` to its `gatsby-config.js`. However, we still check for the old cookie set by `CookieConsentDialog`, and if a user has ever selected No to opt out of tracking, we do not use Tessen. Instead we use Google Analytics to anonymously track page views.

That old cookie is also set for newrelic domains, so if trying to test in a preview build (on a non-newrelic domain), Tessen is not used.

## Acceptance criteria
- [x] Google Analytics code is removed
- [x] The [`tracking.js` utility](https://github.com/newrelic/gatsby-theme-newrelic/blob/c7682d1040caf50318f898af88508f7dbe36d4b1/packages/gatsby-theme-newrelic/src/utils/tracking.js) is removed
- [x] Tessen is used without checking for old cookie
- [x] `CookieConsentDialog` component is removed
- [ ] Ensure tracking behavior complies when a user does not accept OneTrust prompt
- [x] Chat with docs and anlytics stakeholders around upcoming change
- [x] Update theme documentation to reflect these changes

## Related issues / PRs
https://github.com/newrelic/docs-website/issues/3848
https://github.com/newrelic/gatsby-theme-newrelic/issues/347
